stages:
  - prepare
  - build
  - badges

prepare_build_stage:
  stage: prepare
  tags:
    - docker
  image: debian:latest
  script:
    - chmod +x .gitlab-ci-generate-ci-yaml.sh
    - ./.gitlab-ci-generate-ci-yaml.sh
  artifacts:
    paths:
      - .presentations-ci.yml
    expire_in: 1 day 
  variables:
    GIT_SSL_NO_VERIFY: "true"

build_presentations:
  stage: build
  trigger:
    include:
      - artifact: .presentations-ci.yml
        job: prepare_build_stage
    strategy: depend
  variables:
    GIT_SSL_NO_VERIFY: "true"

badges:
  stage: badges
  image: python:3.6.6
  tags:
    - docker
  only:
    refs:
      - main
  script:
    - pip install anybadge
    - anybadge -l " Download PDFs " -v " Commit $CI_COMMIT_SHORT_SHA" -f pdfs.svg -c '#2F586E'
    - anybadge -l " Download Exam Introduction " -v " Commit $CI_COMMIT_SHORT_SHA" -f exam-intro.svg -c '#2F586E'
  artifacts:
    paths:
      - pdfs.svg
      - exam-intro.svg
  
  variables:
    GIT_SSL_NO_VERIFY: "true"


